org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# Zodat ":kern:test" te draaien is zonder dat de Android-module geconfigureerd
# (en dus de Android SDK vereist) wordt.
org.gradle.configureondemand=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
